---
title: "8_予算"
---

# ケース

# 予算管理とは

## 予算管理 (budgetary control)

予算編成方針を指針として，各部門に責任とその責任遂行に必要な資源を財務数字で割り付けて予算を編成するとともに，PDCAサイクルを回すことにより戦略実施を図る管理活動

予算編成方針

長期経営計画→利益計画をベースとして，予算を策定する際の指針を作る

## 予算の目的

主に3つに整理される

1.  計画設定と責任の公式化
2.  調整と伝達
3.  動機付けと業績評価

## 計画設定と責任の公式化

利益計画の責任と実行権限を各部署に割り振り，その実行に必要な資源（お金や人員等）を配分する

## 調整と伝達

個々の管理者の目標が会社全体の目標とせいごうせいをm持つように経営資源をバランスよく活用する

後で出てくる予算編成プロセスの中で，部門から上がってくる目標と全社としての目標を擦り合わせる

策定された予算は，企業の目的，それを分解して各部署に期待するものを金額の形で伝達する。

## 動機付けと業績評価

予算の達成度合いは，即ち期待にどれぐらい応えたのか，責任を果たしたのか，を表す。予算の達成度合いはしばしば部門自体，部門の責任者，そして部門の構成員の評価に使われ，ボーナスや昇給・昇進等に関わる。

それゆえ従業員は，予算達成に向けて努力するようになる。

例え明確に報酬と結びついていなくても，上司や同僚に未達の経緯や理由を説明することを避けるために頑張る。

こういった意味で予算は従業員の動機付けにも役割を果たす。

# 予算の構造と編成

## 予算の構造

大きく分けて

-   経常予算
    -   損益予算
    -   資金予算
-   資本予算

## 予算編成のプロセス

1.  売上高予測
2.  生産量の決定
3.  製造費用と業務費用の推定
4.  キャッシュフロー等の決定
5.  予算の設定

-   通常予算編成は，売上高の予測，売上高予算の設定から始まる。
    -   売上高が決まると生産量が決まり，製造費用が決まり，製造に必要な設備投資が決まる
-   売上高の予測は通常以下のような方法で行われる
    -   ビジネスの状況・市場の状況・製品の製造曲線などをベースにした統計的な予測を立てる
    -   経営幹部や営業からの意見を集めて予測を立てる
    -   売上高に影響するいくつかの要因を分析して，それらの要因の将来の振る舞いを予測する
-   売上が決まったら，製造予算を設定する
    -   売上高予算達成に必要な生産量と在庫
-   生産量 = 当期生産量 + 理想的な期末棚卸量 - 期首棚卸量

## 予算編成日程を組む

予算は毎年策定される。3ヶ月から長いところでは6ヶ月ぐらいかけることも。

事業部・部単位の予算案が作成され，本社の予算編成方針とすり合わせが行われる

## 総合予算を編成する

### 売上高予算・製造高予算・製造在庫予算

出発点は売上高予算：市場動向を踏まえ「どれぐらい売れそうか」を起点に計画を立てる

-   営業部門から積み上げ

製造部門のキャパシティや製造スケジュール，適正な在庫量等を踏まえて製造量に関する計画を立てる

### 製造費用予算・製造原価予算

製造高予算が決まると，製造費用及びそこから仕掛品を増減した製造原価に関する計画を立てる

製造費用予算は，材料消費予算・労務費予算・製造間接費予算に分解してそれぞれ計画が立てられる

-   原価計算で出てくる予算

------------------------------------------------------------------------

### 損益予算

売上原価 = 期首製品有高 + 当期製造原価 - 期末製品有高

なので，製造原価予算と製造在庫予算から売上原価予算が決まる

売上高予算から売上原価予算を差し引くと，売上総利益予算が定まる

### 材料購買予算・材料在庫予算

製造原価予算に関連して，材料予算には，材料消費予算，材料購買予算・材料在庫予算・材料支払予算がある。これらは，それぞれ違う部署が担当する

-   材料購買予算は購買部
-   材料在庫予算は倉庫
-   材料支払い予算は経理？財務？

### 資金予算

材料支払予算・労務費支払予算・経費支払予算は資金予算の一部

資金予算には他にも販売費支払予算・一般管理費支払予算・営業外費用支払予算・設備予算などが含まれる。

また，収入項目として売上債権回収予算・営業外収入予算が含まれる。

これらは，実際の支払いに関連する（利益ではなくキャッシュ）項目で，利益が出ていても支払いが滞る，ということが内容計画される。

### 貸借対照表予算

損益計算書に関連する項目の予算と対応する形でそれぞれ設定される。

# 予算の運用

## 予算目標の設定

-   予算は一般的に，トップが示す利益計画と，現場からの予算案をすり合わせて設定される
-   一旦設定されると業務の指針として，進捗に問題はないか，行動の修正が必要な部分はどこか，といった分析・決定に使われる
-   また，予算は同時に各部署の目標として機能する。目標の達成・未達によって部署やそのメンバーの評価が決まる。評価は長期的な昇給や昇進に影響を与える（可能性がある）
-   特に後者の機能から，従業員は予算を設定する際に影響力を行使しようと考える。予算の駆け引き，予算ゲームと呼ばれる。

## 予算ゲーム

-   目標として予算を設定する際，目標は必ずしも経営者が決める（トップダウン）わけではなく，より現場の状況を把握した各部署が原案を作成する場合が多い（参加型予算）。
    -   より現場の情報を反映した現実的な予算が設定できる
    -   予算編成に関わることで，予算達成に対するコミットメントが高まる
-   しかし，参加型予算では，現場は「費用予算はできる限りたくさん，売上高予算はできるだけ低めに」設定したくなる [@kato2017]
-   現実よりも多めの費用，低めの収益を設定することによって生まれる余裕部分を**予算スラック**という（加登 1999）
-   この予算スラックを作る際の駆け引きを予算ゲーム (budget game)と呼ぶ [@kato2017]

## 予算スラックのパターン

[@kato2017 及び[Ginsburg 1981](https://www.inc.com/magazine/19810901/7191.html)]

**The Gardener**

事前に予算を育て（対策を立て）さまざまな使途を作っておく。派手な資料で巧みに予算を獲得する。予算の使途が明確でなく，まんべんなく予算が使われるので，期待した成果が上がらない

**The Duck Hunter**

予算請求額の中に，本当は必要でない予算項目（囮，decoy）を紛れ込ませる。どの計画が本物で，どの計画が囮なのかを惑わせ，多めの予算を獲得できるよう狙う

**The Entrepreneur**

成功確率の低いプロジェクトを将来のための投資であるとして推して予算獲得を狙う

**The Gambler**

"予算を削れば辞任する"といったハッタリを使いながら予算交渉を行う。ポーカーフェイスで自信家。

**The Surgeon**

十分な予算がなかったから悲惨な現状にある，と主張し，「これ以上削減されたら責任を取れない」と警告する。

**The Good Soldier**

会社の方針と目標に沿った行動をとる会社人間。「上司の采配に従う」，「現状の予算で任務を達成する」という。しかし，このような人でも予算を過大請求したいという願望を持っている。

**The Drowning Man**

いつも不当な扱いを受けていて，溺れそうだ，と主張する。危機感を共有し，予算上の救済を求める。（実際にそれほど深刻なのかどうかは上司にはわからない）

**The Savior**

会社全体を救うための方策として，自部門の予算措置を要求する。（逆に予算措置に応じなければ会社の将来を危うくすると暗示している）

**The Honest Guy**

正直者。このような人のことを信じず予算を削ると Drowning Manに変身する。

## 予算目標の設定

利益計画を立て，予算目標を策定する際にどのような目標をベンチマークにするべきか。

1.  自部門の過去の業績
2.  同業他社・同僚の業績

## 自部門の過去の業績

-   予算目標は基本的に1年以下の単位で測定される
    -   評価は四半期ごとや半年，1年ごと
-   予算目標の達成度合いで評価される従業員は，短期的な目標達成のため長期的な価値を犠牲にするかも知れない。
    -   必要な投資を行わない：研究開発予算を削る，採用を止める
    -   押し売りをする
    -   利益を翌年から持ってくる（費用を翌年に繰越す）
        -   東芝のバイセル取引
-   目標が前年の実績をもとに決められる場合，従業員は目標を超過達成しないよう動機付けられる
    -   今年頑張りすぎると来年の自分の首を絞めることになる
    -   来年を見越して目標の超過達成を防ぐために意図的に努力を減らすことをラチェット効果という[@leone2002; @bouwens2011]
-   自分・自部門の能力を踏まえて目標を設定できる。
-   一方でラチェット効果が起きることが知られている

#### 同業他社・同僚の業績

-   他部門との順位，同業他社業績との比較などの形で目標を立てる。
-   景気の変動や災害など，他者と共通して起こる業績の変動の影響を排除した目標が立てられる。
-   適切な比較対象を見つけないと目標として機能しない [@matsumura2006]
-   協力が必要な部門を比較対象としてしまうと協調行動を取らない可能性も[@holzhacker2019]

## 予算は修正すべきか

このように組み上げられた予算は，各部門に示達され，各部門は予算を指針として業務を行う。

基本的には，予算を指針に，行動を修正，という形で業務が進むが，予算自体を変えるということも検討される。

### メリット

経営環境が大きく変わり，当初の予算では

-   計画・業務の指針としての意味をなさない
-   目標達成が困難すぎ（容易すぎ）て，動機付け効果を発揮できない

といった時，新しい環境に合わせた予算の修正は，役にたつ可能性がある

### デメリット

予算はそもそもより上位の計画を数値に落とし込んだもの。予算を修正すると，より上位の目標と乖離が生じる

従業員は，予算が変更されることを織り込んで行動をするようになる。

-   目標を達成しすぎると，より高い目標に修正されるかもしれない
-   目標が未達でも，それを踏まえて予算目標を下げてくれるかもしれない

# 脱予算経営

Hopeらは，予算の欠点を指摘し，予算を廃し，より軽量なシステムに置き換えることを提案。

現実に，予算は多くの企業にとって運用されているもの。欠点はありながらも必要（横田・妹尾・高田・金子 2013 企業会計）

-   伝統的な予算は，前年度の業績をベースに計画を立て始める。
    -   ここでの前提は，前年度の活動は必要不可欠で続けるべきものだ，ということ。
-   それに対してゼロベース予算は，文字通りゼロから作り始める。
-   組織に蔓延している無駄を排除できる可能性
-   一方で，圧倒的に時間とコストがかかる。
-   「脱予算 Beyond Budgetting」という考え方もある[@hope2003]が，圧倒的多数の企業は予算を使っている [例えば, @yokota2012]

# 予算管理の課題

-   予算を設定する際，それを意思決定の指針として使うのか，目標として使うのか，両方として使うのか？
    -   意思決定の指針としては，より現実的な数値で設定されるのが良い
    -   目標として設定する（予算の達成と人事評価を結びつけて，達成度が高いほど高い評価や報酬を得られるようにして，従業員を動機付ける）場合は，「頑張ったら達成できる」水準で予算が設定されるのが良い [目標設定理論，例えば @locke2002]
-   予算目標は，どちらかというと後者を意識して作られるようだが，それぞれ別々に設定する場合もある [@arnold2019]

# 参考文献
